### ISSUE TITLE
Allow setting compiler options in loader query

### ISSUE THREAD

**Issue by jgoz** [jbrantly/ts-loader#1]
To allow users to set compiler options, you can use [loader-utils](https://github.com/webpack/loader-utils) to parse the loader's [query](http://webpack.github.io/docs/loaders.html#query) into an object. They could be specified like this:

```js
{ test: /\.ts$/, loader: 'ts-loader?target=ES3,module=AMD,-sourceMap' }
```

**Comment by jbrantly** [comment]
Thanks, I'll definitely add this.

**Comment by jbrantly** [comment]
I've added this in v0.2.0 which has been published. One thing to note is I turned sourceMaps off by default (this mimics the behavior of css-loader).

**Comment by jgoz** [comment]
Nice!
