### ISSUE TITLE
Changes not being detected by devServer / hot replacement

### ISSUE THREAD

**Issue by mgutz** [jbrantly/ts-loader#13]
When I change a file in watch mode, webpack seems to build but browser says no changes detected. There is only one typescript file in the project other than the type files. Building in non-watch mode works fine.

version: 0.3.3

**Comment by jbrantly** [comment]
Could you provide some more detail? I just tried this...

app.ts
```
document.write('Hello world')
```

webpack.config.ts
```
module.exports = {
    entry: './app.ts',
    output: {
        path: __dirname,
        filename: 'bundle.js',
    },
    resolve: {
        extensions: ['', '.webpack.js', '.web.js', '.js', '.ts']
    },
    module: {
        loaders: [
            { test: /\.ts$/, loader: 'ts-loader' }
        ]
    }
}
```

index.html
```
<!DOCTYPE html>

<html lang="en">
<body>
    <script src="bundle.js"></script>
</body>
</html>
```

Running `webpack-dev-server` and visiting `http://localhost:8080/webpack-dev-server/` using  WDS v1.8.0 seems to work for me. I'm not using HMR though.

**Comment by jbrantly** [comment]
Going to close this since there hasn't been a comment in some time. If you're still experiencing the issue feel free to reopen.
