### ISSUE TITLE
Can't npm install

### ISSUE THREAD

**Issue by silhouettes** [jbrantly/ts-loader#16]
I can't seem to install the latest version (0.3.4 works fine though). I've tried this on both a windows and a mac machine with the same result complaining about the Typescript dependency. Here is the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'ts-loader' ]
2 info using npm@2.9.1
3 info using node@v0.12.2
4 verbose install initial load of /Users/rich/repos/react-experiment/package.json
5 verbose installManyTop reading scoped package data from /Users/rich/repos/react-experiment/node_modules/babel-core/package.json
6 verbose installManyTop reading scoped package data from /Users/rich/repos/react-experiment/node_modules/babel-loader/package.json
7 verbose installManyTop reading scoped package data from /Users/rich/repos/react-experiment/node_modules/browserify/package.json
8 verbose installManyTop reading scoped package data from /Users/rich/repos/react-experiment/node_modules/gulp/package.json
9 verbose installManyTop reading scoped package data from /Users/rich/repos/react-experiment/node_modules/gulp-concat/package.json
10 verbose installManyTop reading scoped package data from /Users/rich/repos/react-experiment/node_modules/jsx-typescript/package.json
11 verbose installManyTop reading scoped package data from /Users/rich/repos/react-experiment/node_modules/react/package.json
12 verbose installManyTop reading scoped package data from /Users/rich/repos/react-experiment/node_modules/reactify/package.json
13 verbose installManyTop reading scoped package data from /Users/rich/repos/react-experiment/node_modules/vinyl-source-stream/package.json
14 verbose installManyTop reading scoped package data from /Users/rich/repos/react-experiment/node_modules/watchify/package.json
15 verbose installManyTop reading scoped package data from /Users/rich/repos/react-experiment/node_modules/webpack/package.json
16 verbose readDependencies loading dependencies from /Users/rich/repos/react-experiment/package.json
17 silly cache add args [ 'ts-loader', null ]
18 verbose cache add spec ts-loader
19 silly cache add parsed spec { raw: 'ts-loader',
19 silly cache add   scope: null,
19 silly cache add   name: 'ts-loader',
19 silly cache add   rawSpec: '',
19 silly cache add   spec: '*',
19 silly cache add   type: 'range' }
20 silly addNamed ts-loader@*
21 verbose addNamed "*" is a valid semver range for ts-loader
22 silly addNameRange { name: 'ts-loader', range: '*', hasData: false }
23 silly mapToRegistry name ts-loader
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry uri https://registry.npmjs.org/ts-loader
27 verbose addNameRange registry:https://registry.npmjs.org/ts-loader not in flight; fetching
28 verbose request uri https://registry.npmjs.org/ts-loader
29 verbose request no auth needed
30 info attempt registry request try #1 at 2:46:45 PM
31 verbose request id 01ae7f3b603eef89
32 verbose etag "66CFYLWB7QSOXNDOLP2OJ0LZ8"
33 http request GET https://registry.npmjs.org/ts-loader
34 http 304 https://registry.npmjs.org/ts-loader
35 silly get cb [ 304,
35 silly get   { date: 'Fri, 08 May 2015 21:46:45 GMT',
35 silly get     via: '1.1 varnish',
35 silly get     'last-modified': 'Fri, 08 May 2015 21:46:45 GMT',
35 silly get     'cache-control': 'max-age=60',
35 silly get     etag: '"66CFYLWB7QSOXNDOLP2OJ0LZ8"',
35 silly get     age: '0',
35 silly get     connection: 'keep-alive',
35 silly get     'x-served-by': 'cache-lax1434-LAX',
35 silly get     'x-cache': 'MISS',
35 silly get     'x-cache-hits': '0',
35 silly get     'x-timer': 'S1431121605.570647,VS0,VE146',
35 silly get     vary: 'Accept' } ]
36 verbose etag https://registry.npmjs.org/ts-loader from cache
37 verbose get saving ts-loader to /Users/rich/.npm/registry.npmjs.org/ts-loader/.cache.json
38 silly addNameRange number 2 { name: 'ts-loader', range: '*', hasData: true }
39 silly addNameRange versions [ 'ts-loader',
39 silly addNameRange   [ '0.1.0',
39 silly addNameRange     '0.2.0',
39 silly addNameRange     '0.2.1',
39 silly addNameRange     '0.2.2',
39 silly addNameRange     '0.2.3',
39 silly addNameRange     '0.3.0',
39 silly addNameRange     '0.3.1',
39 silly addNameRange     '0.3.2',
39 silly addNameRange     '0.3.3',
39 silly addNameRange     '0.3.4',
39 silly addNameRange     '0.4.0',
39 silly addNameRange     '0.4.1' ] ]
40 silly addNamed ts-loader@0.4.1
41 verbose addNamed "0.4.1" is a plain semver version for ts-loader
42 silly cache afterAdd ts-loader@0.4.1
43 verbose afterAdd /Users/rich/.npm/ts-loader/0.4.1/package/package.json not in flight; writing
44 verbose afterAdd /Users/rich/.npm/ts-loader/0.4.1/package/package.json written
45 silly install resolved [ { name: 'ts-loader',
45 silly install resolved     version: '0.4.1',
45 silly install resolved     description: 'TypeScript loader for webpack',
45 silly install resolved     main: 'index.js',
45 silly install resolved     scripts:
45 silly install resolved      { pretest: 'tsc index.ts --module commonjs',
45 silly install resolved        test: 'node ./node_modules/mocha/bin/mocha --reporter spec test/run.js',
45 silly install resolved        prepublish: 'tsc index.ts --module commonjs' },
45 silly install resolved     repository:
45 silly install resolved      { type: 'git',
45 silly install resolved        url: 'git+https://github.com/jbrantly/ts-loader.git' },
45 silly install resolved     keywords:
45 silly install resolved      [ 'ts-loader',
45 silly install resolved        'typescript-loader',
45 silly install resolved        'webpack',
45 silly install resolved        'loader',
45 silly install resolved        'typescript',
45 silly install resolved        'ts' ],
45 silly install resolved     author:
45 silly install resolved      { name: 'James Brantly',
45 silly install resolved        email: 'james@jbrantly.com',
45 silly install resolved        url: 'http://www.jbrantly.com/' },
45 silly install resolved     license: 'MIT',
45 silly install resolved     bugs: { url: 'https://github.com/jbrantly/ts-loader/issues' },
45 silly install resolved     homepage: 'https://github.com/jbrantly/ts-loader',
45 silly install resolved     dependencies:
45 silly install resolved      { colors: '^1.0.3',
45 silly install resolved        'loader-utils': '^0.2.6',
45 silly install resolved        'object-assign': '^2.0.0',
45 silly install resolved        typescript: '~1.5.0' },
45 silly install resolved     devDependencies:
45 silly install resolved      { 'jsx-typescript': '^1.5.0-alpha.4',
45 silly install resolved        mocha: '^2.1.0',
45 silly install resolved        webpack: '^1.5.3' },
45 silly install resolved     gitHead: 'c4394142f71e1565f10b0fd24225f2ce615ee3b8',
45 silly install resolved     _id: 'ts-loader@0.4.1',
45 silly install resolved     _shasum: '786772f4eec0a9e2891ca18cbcc188518a2c701b',
45 silly install resolved     _from: 'ts-loader@*',
45 silly install resolved     _npmVersion: '1.4.28',
45 silly install resolved     _npmUser: { name: 'jbrantly', email: 'james@jbrantly.com' },
45 silly install resolved     maintainers: [ [Object] ],
45 silly install resolved     dist:
45 silly install resolved      { shasum: '786772f4eec0a9e2891ca18cbcc188518a2c701b',
45 silly install resolved        tarball: 'http://registry.npmjs.org/ts-loader/-/ts-loader-0.4.1.tgz' },
45 silly install resolved     directories: {},
45 silly install resolved     _resolved: 'https://registry.npmjs.org/ts-loader/-/ts-loader-0.4.1.tgz',
45 silly install resolved     readme: 'ERROR: No README data found!' } ]
46 info install ts-loader@0.4.1 into /Users/rich/repos/react-experiment
47 info installOne ts-loader@0.4.1
48 verbose installOne of ts-loader to /Users/rich/repos/react-experiment not in flight; installing
49 verbose lock using /Users/rich/.npm/_locks/ts-loader-3e1df6fff3206756.lock for /Users/rich/repos/react-experiment/node_modules/ts-loader
50 silly install write writing ts-loader 0.4.1 to /Users/rich/repos/react-experiment/node_modules/ts-loader
51 verbose unbuild node_modules/ts-loader
52 silly gentlyRm /Users/rich/repos/react-experiment/node_modules/ts-loader is being purged from base /Users/rich/repos/react-experiment
53 verbose gentlyRm don't care about contents; nuking /Users/rich/repos/react-experiment/node_modules/ts-loader
54 verbose tar unpack /Users/rich/.npm/ts-loader/0.4.1/package.tgz
55 verbose tar unpacking to /Users/rich/repos/react-experiment/node_modules/ts-loader
56 silly gentlyRm /Users/rich/repos/react-experiment/node_modules/ts-loader is being purged
57 verbose gentlyRm don't care about contents; nuking /Users/rich/repos/react-experiment/node_modules/ts-loader
58 silly gunzTarPerm modes [ '755', '644' ]
59 silly gunzTarPerm extractEntry package.json
60 silly gunzTarPerm modified mode [ 'package.json', 436, 420 ]
61 silly gunzTarPerm extractEntry .npmignore
62 silly gunzTarPerm modified mode [ '.npmignore', 436, 420 ]
63 silly gunzTarPerm extractEntry README.md
64 silly gunzTarPerm modified mode [ 'README.md', 436, 420 ]
65 silly gunzTarPerm extractEntry LICENSE
66 silly gunzTarPerm modified mode [ 'LICENSE', 436, 420 ]
67 silly gunzTarPerm extractEntry index.js
68 silly gunzTarPerm modified mode [ 'index.js', 436, 420 ]
69 silly gunzTarPerm extractEntry CHANGELOG.md
70 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 436, 420 ]
71 silly gunzTarPerm extractEntry UPGRADE.md
72 silly gunzTarPerm modified mode [ 'UPGRADE.md', 436, 420 ]
73 verbose write writing to /Users/rich/repos/react-experiment/node_modules/ts-loader/package.json
74 info preinstall ts-loader@0.4.1
75 verbose readDependencies loading dependencies from /Users/rich/repos/react-experiment/node_modules/ts-loader/package.json
76 silly prepareForInstallMany adding colors@^1.0.3 from ts-loader dependencies
77 silly prepareForInstallMany adding loader-utils@^0.2.6 from ts-loader dependencies
78 silly prepareForInstallMany adding object-assign@^2.0.0 from ts-loader dependencies
79 silly prepareForInstallMany adding typescript@~1.5.0 from ts-loader dependencies
80 verbose readDependencies loading dependencies from /Users/rich/repos/react-experiment/node_modules/ts-loader/package.json
81 silly cache add args [ 'colors@^1.0.3', null ]
82 verbose cache add spec colors@^1.0.3
83 silly cache add args [ 'loader-utils@^0.2.6', null ]
84 verbose cache add spec loader-utils@^0.2.6
85 silly cache add parsed spec { raw: 'colors@^1.0.3',
85 silly cache add   scope: null,
85 silly cache add   name: 'colors',
85 silly cache add   rawSpec: '^1.0.3',
85 silly cache add   spec: '>=1.0.3 <2.0.0',
85 silly cache add   type: 'range' }
86 silly addNamed colors@>=1.0.3 <2.0.0
87 verbose addNamed ">=1.0.3 <2.0.0" is a valid semver range for colors
88 silly addNameRange { name: 'colors', range: '>=1.0.3 <2.0.0', hasData: false }
89 silly mapToRegistry name colors
90 silly mapToRegistry using default registry
91 silly mapToRegistry registry https://registry.npmjs.org/
92 silly mapToRegistry uri https://registry.npmjs.org/colors
93 verbose addNameRange registry:https://registry.npmjs.org/colors not in flight; fetching
94 silly cache add parsed spec { raw: 'loader-utils@^0.2.6',
94 silly cache add   scope: null,
94 silly cache add   name: 'loader-utils',
94 silly cache add   rawSpec: '^0.2.6',
94 silly cache add   spec: '>=0.2.6 <0.3.0',
94 silly cache add   type: 'range' }
95 silly addNamed loader-utils@>=0.2.6 <0.3.0
96 verbose addNamed ">=0.2.6 <0.3.0" is a valid semver range for loader-utils
97 silly addNameRange { name: 'loader-utils', range: '>=0.2.6 <0.3.0', hasData: false }
98 silly mapToRegistry name loader-utils
99 silly mapToRegistry using default registry
100 silly mapToRegistry registry https://registry.npmjs.org/
101 silly mapToRegistry uri https://registry.npmjs.org/loader-utils
102 verbose addNameRange registry:https://registry.npmjs.org/loader-utils not in flight; fetching
103 silly cache add args [ 'object-assign@^2.0.0', null ]
104 verbose cache add spec object-assign@^2.0.0
105 silly cache add parsed spec { raw: 'object-assign@^2.0.0',
105 silly cache add   scope: null,
105 silly cache add   name: 'object-assign',
105 silly cache add   rawSpec: '^2.0.0',
105 silly cache add   spec: '>=2.0.0 <3.0.0',
105 silly cache add   type: 'range' }
106 silly addNamed object-assign@>=2.0.0 <3.0.0
107 verbose addNamed ">=2.0.0 <3.0.0" is a valid semver range for object-assign
108 silly addNameRange { name: 'object-assign',
108 silly addNameRange   range: '>=2.0.0 <3.0.0',
108 silly addNameRange   hasData: false }
109 silly mapToRegistry name object-assign
110 silly mapToRegistry using default registry
111 silly mapToRegistry registry https://registry.npmjs.org/
112 silly mapToRegistry uri https://registry.npmjs.org/object-assign
113 verbose addNameRange registry:https://registry.npmjs.org/object-assign not in flight; fetching
114 silly cache add args [ 'typescript@~1.5.0', null ]
115 verbose cache add spec typescript@~1.5.0
116 silly cache add parsed spec { raw: 'typescript@~1.5.0',
116 silly cache add   scope: null,
116 silly cache add   name: 'typescript',
116 silly cache add   rawSpec: '~1.5.0',
116 silly cache add   spec: '>=1.5.0 <1.6.0',
116 silly cache add   type: 'range' }
117 silly addNamed typescript@>=1.5.0 <1.6.0
118 verbose addNamed ">=1.5.0 <1.6.0" is a valid semver range for typescript
119 silly addNameRange { name: 'typescript', range: '>=1.5.0 <1.6.0', hasData: false }
120 silly mapToRegistry name typescript
121 silly mapToRegistry using default registry
122 silly mapToRegistry registry https://registry.npmjs.org/
123 silly mapToRegistry uri https://registry.npmjs.org/typescript
124 verbose addNameRange registry:https://registry.npmjs.org/typescript not in flight; fetching
125 verbose request uri https://registry.npmjs.org/colors
126 verbose request no auth needed
127 info attempt registry request try #1 at 2:46:45 PM
128 verbose etag "4T0EZRMD070K0EW827B38XR8G"
129 http request GET https://registry.npmjs.org/colors
130 verbose request uri https://registry.npmjs.org/typescript
131 verbose request no auth needed
132 info attempt registry request try #1 at 2:46:45 PM
133 verbose etag "5HTGGVSQOAABIHTKL08UVTAD9"
134 http request GET https://registry.npmjs.org/typescript
135 verbose request uri https://registry.npmjs.org/loader-utils
136 verbose request no auth needed
137 info attempt registry request try #1 at 2:46:45 PM
138 verbose etag "BKY6H9I5OCVZVB1G07Q6PP85Y"
139 http request GET https://registry.npmjs.org/loader-utils
140 verbose request uri https://registry.npmjs.org/object-assign
141 verbose request no auth needed
142 info attempt registry request try #1 at 2:46:45 PM
143 verbose etag "1WKYIZVJKREFK4HYXVMP3C9MW"
144 http request GET https://registry.npmjs.org/object-assign
145 http 304 https://registry.npmjs.org/colors
146 silly get cb [ 304,
146 silly get   { date: 'Fri, 08 May 2015 21:46:45 GMT',
146 silly get     via: '1.1 varnish',
146 silly get     'last-modified': 'Fri, 08 May 2015 21:21:34 GMT',
146 silly get     'cache-control': 'max-age=60',
146 silly get     etag: '"4T0EZRMD070K0EW827B38XR8G"',
146 silly get     age: '39',
146 silly get     connection: 'keep-alive',
146 silly get     'x-served-by': 'cache-lax1428-LAX',
146 silly get     'x-cache': 'HIT',
146 silly get     'x-cache-hits': '344',
146 silly get     'x-timer': 'S1431121605.997762,VS0,VE0',
146 silly get     vary: 'Accept' } ]
147 verbose etag https://registry.npmjs.org/colors from cache
148 verbose get saving colors to /Users/rich/.npm/registry.npmjs.org/colors/.cache.json
149 http 304 https://registry.npmjs.org/object-assign
150 silly get cb [ 304,
150 silly get   { date: 'Fri, 08 May 2015 21:46:46 GMT',
150 silly get     via: '1.1 varnish',
150 silly get     'cache-control': 'max-age=60',
150 silly get     etag: '"1WKYIZVJKREFK4HYXVMP3C9MW"',
150 silly get     age: '55',
150 silly get     connection: 'keep-alive',
150 silly get     'x-served-by': 'cache-lax1423-LAX',
150 silly get     'x-cache': 'HIT',
150 silly get     'x-cache-hits': '3',
150 silly get     'x-timer': 'S1431121606.003761,VS0,VE0',
150 silly get     vary: 'Accept' } ]
151 verbose etag https://registry.npmjs.org/object-assign from cache
152 verbose get saving object-assign to /Users/rich/.npm/registry.npmjs.org/object-assign/.cache.json
153 http 304 https://registry.npmjs.org/loader-utils
154 silly get cb [ 304,
154 silly get   { date: 'Fri, 08 May 2015 21:46:46 GMT',
154 silly get     via: '1.1 varnish',
154 silly get     'cache-control': 'max-age=60',
154 silly get     etag: '"BKY6H9I5OCVZVB1G07Q6PP85Y"',
154 silly get     age: '49',
154 silly get     connection: 'keep-alive',
154 silly get     'x-served-by': 'cache-lax1421-LAX',
154 silly get     'x-cache': 'HIT',
154 silly get     'x-cache-hits': '51',
154 silly get     'x-timer': 'S1431121606.006522,VS0,VE0',
154 silly get     vary: 'Accept' } ]
155 verbose etag https://registry.npmjs.org/loader-utils from cache
156 verbose get saving loader-utils to /Users/rich/.npm/registry.npmjs.org/loader-utils/.cache.json
157 silly addNameRange number 2 { name: 'colors', range: '>=1.0.3 <2.0.0', hasData: true }
158 silly addNameRange versions [ 'colors',
158 silly addNameRange   [ '0.3.0',
158 silly addNameRange     '0.5.0',
158 silly addNameRange     '0.5.1',
158 silly addNameRange     '0.6.0',
158 silly addNameRange     '0.6.0-1',
158 silly addNameRange     '0.6.1',
158 silly addNameRange     '0.6.2',
158 silly addNameRange     '1.0.0',
158 silly addNameRange     '1.0.1',
158 silly addNameRange     '1.0.2',
158 silly addNameRange     '1.0.3',
158 silly addNameRange     '1.1.0' ] ]
159 silly addNamed colors@1.1.0
160 verbose addNamed "1.1.0" is a plain semver version for colors
161 silly addNameRange number 2 { name: 'object-assign', range: '>=2.0.0 <3.0.0', hasData: true }
162 silly addNameRange versions [ 'object-assign',
162 silly addNameRange   [ '0.1.0',
162 silly addNameRange     '0.1.1',
162 silly addNameRange     '0.1.2',
162 silly addNameRange     '0.2.0',
162 silly addNameRange     '0.2.1',
162 silly addNameRange     '0.2.2',
162 silly addNameRange     '0.3.0',
162 silly addNameRange     '0.3.1',
162 silly addNameRange     '0.4.0',
162 silly addNameRange     '1.0.0',
162 silly addNameRange     '2.0.0' ] ]
163 silly addNamed object-assign@2.0.0
164 verbose addNamed "2.0.0" is a plain semver version for object-assign
165 silly addNameRange number 2 { name: 'loader-utils', range: '>=0.2.6 <0.3.0', hasData: true }
166 silly addNameRange versions [ 'loader-utils',
166 silly addNameRange   [ '0.1.0',
166 silly addNameRange     '0.1.1',
166 silly addNameRange     '0.1.2',
166 silly addNameRange     '0.2.0',
166 silly addNameRange     '0.2.1',
166 silly addNameRange     '0.2.2',
166 silly addNameRange     '0.2.3',
166 silly addNameRange     '0.2.4',
166 silly addNameRange     '0.2.5',
166 silly addNameRange     '0.2.6',
166 silly addNameRange     '0.2.7' ] ]
167 silly addNamed loader-utils@0.2.7
168 verbose addNamed "0.2.7" is a plain semver version for loader-utils
169 silly cache afterAdd colors@1.1.0
170 verbose afterAdd /Users/rich/.npm/colors/1.1.0/package/package.json not in flight; writing
171 silly cache afterAdd object-assign@2.0.0
172 verbose afterAdd /Users/rich/.npm/object-assign/2.0.0/package/package.json not in flight; writing
173 silly cache afterAdd loader-utils@0.2.7
174 verbose afterAdd /Users/rich/.npm/loader-utils/0.2.7/package/package.json not in flight; writing
175 verbose afterAdd /Users/rich/.npm/colors/1.1.0/package/package.json written
176 verbose afterAdd /Users/rich/.npm/loader-utils/0.2.7/package/package.json written
177 verbose afterAdd /Users/rich/.npm/object-assign/2.0.0/package/package.json written
178 http 304 https://registry.npmjs.org/typescript
179 silly get cb [ 304,
179 silly get   { date: 'Fri, 08 May 2015 21:46:46 GMT',
179 silly get     via: '1.1 varnish',
179 silly get     'last-modified': 'Fri, 08 May 2015 21:46:46 GMT',
179 silly get     'cache-control': 'max-age=60',
179 silly get     etag: '"5HTGGVSQOAABIHTKL08UVTAD9"',
179 silly get     age: '0',
179 silly get     connection: 'keep-alive',
179 silly get     'x-served-by': 'cache-lax1432-LAX',
179 silly get     'x-cache': 'HIT',
179 silly get     'x-cache-hits': '1',
179 silly get     'x-timer': 'S1431121606.000459,VS0,VE44',
179 silly get     vary: 'Accept' } ]
180 verbose etag https://registry.npmjs.org/typescript from cache
181 verbose get saving typescript to /Users/rich/.npm/registry.npmjs.org/typescript/.cache.json
182 silly addNameRange number 2 { name: 'typescript', range: '>=1.5.0 <1.6.0', hasData: true }
183 silly addNameRange versions [ 'typescript',
183 silly addNameRange   [ '0.8.0',
183 silly addNameRange     '0.8.1',
183 silly addNameRange     '0.8.1-1',
183 silly addNameRange     '0.8.2',
183 silly addNameRange     '0.8.3',
183 silly addNameRange     '0.9.0',
183 silly addNameRange     '0.9.0-1',
183 silly addNameRange     '0.9.1',
183 silly addNameRange     '0.9.1-1',
183 silly addNameRange     '0.9.5',
183 silly addNameRange     '0.9.7',
183 silly addNameRange     '1.0.0',
183 silly addNameRange     '1.0.1',
183 silly addNameRange     '1.1.0-1',
183 silly addNameRange     '1.3.0',
183 silly addNameRange     '1.4.1',
183 silly addNameRange     '1.5.0-alpha',
183 silly addNameRange     '1.5.0-beta' ] ]
184 verbose about to build /Users/rich/repos/react-experiment/node_modules/ts-loader
185 verbose unlock done using /Users/rich/.npm/_locks/ts-loader-3e1df6fff3206756.lock for /Users/rich/repos/react-experiment/node_modules/ts-loader
186 verbose stack Error: No compatible version found: typescript@'>=1.5.0 <1.6.0'
186 verbose stack Valid install targets:
186 verbose stack ["0.8.0","0.8.1","0.8.1-1","0.8.2","0.8.3","0.9.0","0.9.0-1","0.9.1","0.9.1-1","0.9.5","0.9.7","1.0.0","1.0.1","1.1.0-1","1.3.0","1.4.1","1.5.0-alpha","1.5.0-beta"]
186 verbose stack
186 verbose stack     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:262:12)
186 verbose stack     at next (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:241:17)
186 verbose stack     at setData (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:218:5)
186 verbose stack     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
186 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
186 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:173:7)
186 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
187 verbose cwd /Users/rich/repos/react-experiment
188 error Darwin 14.3.0
189 error argv "node" "/usr/local/bin/npm" "install" "--save-dev" "ts-loader"
190 error node v0.12.2
191 error npm  v2.9.1
192 error code ETARGET
193 error notarget No compatible version found: typescript@'>=1.5.0 <1.6.0'
193 error notarget Valid install targets:
193 error notarget ["0.8.0","0.8.1","0.8.1-1","0.8.2","0.8.3","0.9.0","0.9.0-1","0.9.1","0.9.1-1","0.9.5","0.9.7","1.0.0","1.0.1","1.1.0-1","1.3.0","1.4.1","1.5.0-alpha","1.5.0-beta"]
193 error notarget
193 error notarget This is most likely not a problem with npm itself.
193 error notarget In most cases you or one of your dependencies are requesting
193 error notarget a package version that doesn't exist.
193 error notarget
193 error notarget It was specified as a dependency of 'ts-loader'
194 verbose exit [ 1, true ]
195 verbose unbuild node_modules/ts-loader
196 info preuninstall ts-loader@0.4.1
197 info uninstall ts-loader@0.4.1
198 verbose unbuild rmStuff ts-loader@0.4.1 from /Users/rich/repos/react-experiment/node_modules
199 info postuninstall ts-loader@0.4.1
200 silly gentlyRm /Users/rich/repos/react-experiment/node_modules/ts-loader is being purged from base /Users/rich/repos/react-experiment
201 verbose gentlyRm don't care about contents; nuking /Users/rich/repos/react-experiment/node_modules/ts-loader
202 silly vacuum-fs purging /Users/rich/repos/react-experiment/node_modules/ts-loader
203 silly vacuum-fs quitting because other entries in /Users/rich/repos/react-experiment/node_modules

**Comment by jbrantly** [comment]
I think this is related to #15. I'll be pushing a new version to NPM this evening with the fix. Thanks for reporting and sorry for the inconvenience.

**Comment by jbrantly** [comment]
I just published v0.4.2 which I believe fixes this issue.
