### ISSUE TITLE
noLib option in tsconfig.json

### ISSUE THREAD

**Issue by use-strict** [jbrantly/ts-loader#19]
The "noLib" compiler option doesn't work. It looks like the lib.*.d.ts file is manually added from index.js:71-75.

I don't fully understand the intent here, but from what I read on the TypeScript docs, if the files option is not specified, then the whole directory is recursively included. I assume you are including the lib manually because there is no "exclude" option and you don't want to recursively include everything.

Ideally, there should be no preprocessing of the "tsconfig.json" file. At the very least, manually check for "noLib" and add an empty dummy file instead, to override the default behavior.

**Comment by jbrantly** [comment]
I am manually including lib.d.ts because the APIs that the loader calls doesn't do it. In other words, if I didn't load it manually then they simply wouldn't be loaded. However, you're absolutely right that the loader should respect the "noLib" option. I'll have to fix that.

If you don't include the `files` option in tsconfig.json then all bets are off. The directory is recursively included and that can sometimes pull in stuff that you don't want. My recommendation is to use `files` to add declaration files that you need, or just an empty array if you don't need any.

**Comment by use-strict** [comment]
I suspected that. That will probably have to hold until TS 1.6 comes out, which supports "exclude" option. Still, it would be nice to respect the "noLib" option. There are cases, for example, when you want to include the es6 lib instead even in es5 target mode (when using shims).

**Comment by jbrantly** [comment]
This has been published in v0.4.4. There is a slightly weird thing where some errors are reported like `Cannot find global type 'Array'.`. I believe some of this is changing for TS 1.5 stable so I'm just going to take a "wait and see" approach. The errors don't break anything. I'm going to leave this issue open until that is resolved though.

**Comment by jbrantly** [comment]
Apparently those errors are intended. Using both the TypeScript 1.5 beta and the nightly build tsc results in the same errors:

```
~/ts-loader/test/nolib$ tsc app.ts --noLib
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
```

I guess their intention is that if you use noLib you should supply definitions for these yourself? I've brought up for discussion at Microsoft/TypeScript#3930. In either case it's not an issue with ts-loader so going to go ahead and close this as fixed.

**Comment by use-strict** [comment]
Yes, the purpose of this option is to be able to supply your own "lib.d.ts" file instead of the bundled one. This is particularly useful when you want to use the old TS 1.4 lib for backwards compatibility with older DefinitelyTyped definitions.

**Comment by jbrantly** [comment]
Yea, I'm just surprised that an empty program (empty source file, no lib files) will throw errors. Doesn't seem to be documented anywhere. *shrug* no biggie.
