### ISSUE TITLE
noImplicitAny

### ISSUE THREAD

**Issue by altano** [jbrantly/ts-loader#2]
I would like to use --no-implicit-any, can you expose this as an option?

Ideally, you would allow passing through options the loader doesn't know about to Typescript, so one wouldn't need to make such requests in the future, if possible?

**Comment by jbrantly** [comment]
I've added this in v0.2.3 and published to npm.

Regarding pass-through options, it's a neat idea. It could be kind of crappy if someone was using an undocumented option in one way and then we added first class support for the option in another way and it broke.

FWIW here's the list of available options as of now: https://github.com/Microsoft/TypeScript/blob/9f49a1637a1afc1f7e0953a5748e5088e91dc777/bin/typescript.d.ts#L1127

I don't think it will be unreasonable to just add first class support for the options which make sense in the context of webpack. That said I'm not completely opposed to the idea so perhaps if it becomes an issue.
