### ISSUE TITLE
Errors in d.ts files not reported

### ISSUE THREAD

**Issue by use-strict** [jbrantly/ts-loader#20]
There are "d.ts" files in my project which have some errors. These kind of errors are not accessible from the webpack API callback and are only written to the console. The code responsible for this seems to be at line 177 in index.js. The errors are logged after the compilation is done, so the callback doesn't see them. Not sure if intended or not, but there is no way for me to retrieve them, other that hackish regex matching on stdout.

I'm currently working on a watcher to integrate the webpack build with PhpStorm and I need to output errors in a strict format ($file$ ($line$, $col$): $message$) without other redundant output.

**Comment by jbrantly** [comment]
I figured out a way to have .d.ts errors reported right alongside all of the other errors. Additionally I've added extra data to errors generated by ts-loader.  In particular I've added `file`, `rawMessage` and `location` properties. See 6f718c9 for an example of usage.
