### ISSUE TITLE
webpack --watch not always detecting changes when you only change type information

### ISSUE THREAD

**Issue by flyon** [jbrantly/ts-loader#21]
When I run webpack --watch which uses ts-loader and ts-jsx-loader and I come across an typescript error, then sometimes when I change some TS code, the watcher does not trigger a new compilation run, and thus I don't see updated webpack output to tell me if the error is now solved. 

I think it relates to Typescript specific changes that do not affect the JS output. 
for example if I get this error:

```Type 'SpecialType' is not assignable to type 'GeneralType'.```

And I then change this:

```var x:SpecialType = foo.getSomething()```

to

```var x:SpecialType = <SpecialType> foo.getSomething()```

the watcher does not trigger a new compilation.
But if I remove the entire line it does (and ofcourse it shows me new errors because the line is missing).. then when I put the line back the watcher triggers again a new compilation and I finally see that my error is resolved.

So at the moment I often have to manually remove lines, save, and put them back, and save to trigger a compilation.
I'm not certain wether this is a bug of webpack or of ts-loader, but I'm expecting the ladder.

**Comment by jbrantly** [comment]
This took quite a while to track down but I believe I've fixed it in v0.4.4. Thanks for reporting, I think this fix makes the watch mode much easier to work with.
