### ISSUE TITLE
support for --jsx flags

### ISSUE THREAD

**Issue by prabirshrestha** [jbrantly/ts-loader#23]
It would be great to have support for `--jsx` flags. https://github.com/Microsoft/TypeScript/pull/3564

```javascript
{ test: /\.ts$/, loader: 'ts-loader?jsx=KIND' }
```

where `KIND` is `preserve` or `react`

**Comment by jbrantly** [comment]
Support for specifying the `jsx` option in the tsconfig.json file is already included in that PR. Using tsconfig.json is the preferred (and only) way to specify TypeScript-related options with this loader. Basically you'll be able to specify the jsx option without any changes to ts-loader once that lands.

**Comment by jbrantly** [comment]
Just for reference, I've [created a JSX test](https://github.com/jbrantly/ts-loader/tree/master/test/jsx) that shows how to set the option in the tsconfig.json file.
