### ISSUE TITLE
Accessors are only available when targeting ECMAScript 5 and higher 

### ISSUE THREAD

**Issue by deryl27** [jbrantly/ts-loader#25]
How to provide target to ES5 while using ts-loader ??

**Comment by jbrantly** [comment]
By using a [tsconfig.json](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json) file.

**Comment by jbrantly** [comment]
You would want something like this:

```
{
  "compilerOptions": {
    "target": "es5"
  }
  "files": []
}
```

**Comment by deryl27** [comment]
@jbrantly  Thanks It works

**Comment by jakeNiemiec** [comment]
Thank you. This is currently the highest google result for the error message. 

For me, [the migration guide for angular-cli is missing `"target": "es5"`](https://github.com/angular/angular-cli/wiki/stories-rc.0-update)

**Comment by attilacsanyi** [comment]
@jakeNiemiec you are right that the main (in root folder) `tsconfig.json` does not contain the `"target": "es5"`, but cli have specific derived `tsconfig.app.json` and `tsconfig.spec.json` configs specified under **src** which both contained the target.

BTW I had to specify the `"target": "es5"` in the root to make it work in VSCode and remove the specific `target` lines from the derived once.

Thanks for the hint anyway.

**Comment by dmijatovic** [comment]
Hi,
I had same problem after updating angular-cli as jakeNiemiec. In my case I only needed to add the target line in tsconfig.json in the root folder and restart VSC.

**Comment by SOHELAHMED7** [comment]
If you are dealing with just a single file and not a project set `--target ES2016`. For eg

`$ tsc --target ES2016 /filepath/filename.ts --watch`


[ref](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

**Comment by Gideon877** [comment]
Very Helpful

**Comment by jorgematheus** [comment]
nice :D

**Comment by yoni333** [comment]
if you input a file to tsc in command line it ignore the tsconfig.json and you need to insert a flag for each config you want( e.g --target ES2016) .
but if you not input ant file in the command line and just add the file in the tsconfig.json tsc will read the config file
[stackoverflow](https://stackoverflow.com/a/46722359/2613863)
[ts docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)

**Comment by Joon-S** [comment]
@SOHELAHMED7 Thank you :)

**Comment by ilmoralito** [comment]
Thanks @SOHELAHMED7
