### ISSUE TITLE
Update example to mention how to use require.ensure().

### ISSUE THREAD

**Issue by ngbrown** [jbrantly/ts-loader#26]
When using ts-loader working with ntypescript for tsx compilation, I ran into a bit of problem doing code-splitting.  I got it working easily enough using `import Home = require("./home")` at the top of the file, but there is no code-splitting. When implementing code-splitting via `require.ensure()` like this:

```ts
  if (!location.hash || location.hash.length === 1) {
    require.ensure([], function () {
      var Home = require("./home");
      React.render(<Home/>, document.getElementById("app"));
    });
  }
```

I get errors.  I can update to the `any` type:

```ts
      var Home = require<any>("./home");
```

But there is then no checking for props.  After much experimentation, it seems this works:

```ts
import Home = require("./home");
```

at the top and then use `typeof`:

```ts
      var Home = require<typeof Home>("./home");
```

**Comment by jbrantly** [comment]
This is somewhat of a TypeScript thing, but I see your point about documenting it to make it easier. The basic idea is that you can `import` a module in TypeScript and as long as you don't directly use it, it will actually be removed from the TypeScript output. `typeof` is "safe" for this purpose. Here's an example straight from TypeScript docs: https://github.com/Microsoft/TypeScript/wiki/Modules#dynamic-module-loading-in-nodejs

Also, just to be clear: you will need to add definitions for `require.ensure`, etc as noted in the README.

I'll see about adding a unit test for it and go into a bit more detail in the README. Thanks!

**Comment by ngbrown** [comment]
I'm just starting on React and haven't used TypeScript's dynamic loading modules before.  I was looking at those TypeScript module documents, but didn't quite make the connection with what react is trying to do and the documents.

**Comment by jbrantly** [comment]
I've updated the README to add a link to an example that illustrates how to do this. Thanks for the feedback!
