### ISSUE TITLE
Doesn't work with named external modules in d.ts files

### ISSUE THREAD

**Issue by stkb** [jbrantly/ts-loader#3]
I tried using ts-loader but immediately got this error:
```
Module build failed: Error: Cannot resolve module 'stream' in C:\...\typings\request
    at innerCallback (C:\...\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver
.js:80:16)
    at loggingCallbackWrapper (C:\...\node_modules\webpack\node_modules\enhanced-resolve\lib
\createInnerCallback.js:20:19)
    at C:\...\node_modules\webpack\node_modules\tapable\lib\Tapable.js:138:6
    at C:\...\node_modules\webpack\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlu
gin.js:53:23
    at C:\...\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:210:15
    at C:\...\node_modules\webpack\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlu
gin.js:44:26
    at loggingCallbackWrapper (C:\...\node_modules\webpack\node_modules\enhanced-resolve\lib
\createInnerCallback.js:20:19)
    at C:\...\node_modules\webpack\node_modules\tapable\lib\Tapable.js:138:6
    at C:\...\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:104:33
    at C:\...\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:210:15
```
It can't resolve any named modules (declare module "somemodule" { ...) in node.d.ts or .d.ts files. Project compiles fine with tsc 1.4.1. Can provide a smaller example if needed.

(Also tried typescript-loader but it had this same problem)

**Comment by jbrantly** [comment]
webpack bundles the modules you import together, so it needs to be able to actually find (resolve) those modules. In this case you did something like `import stream = require('stream')`. TypeScript is fine with that because it doesn't need to go and get whatever code sits behind the 'stream' module. However, webpack does go and try to find that code and that is what's failing. You would get the same error if TypeScript wasn't involved at all.

I'm not super familiar with webpack's ability to include native node modules like stream. It may not be possible.

**Comment by jgoz** [comment]
http://webpack.github.io/docs/configuration.html#node

You can try enabling it with:
```js
{
  node: {
    streams: true
  }
}
```

But it probably won't work, especially if streams uses any native libs (not sure). You will likely need to find a web-safe streams library.

**Comment by jbrantly** [comment]
Thanks @jgoz. I was having a hard time finding documentation to that effect.

**Comment by stkb** [comment]
I should have added, that webpack compiles my code fine if I first compile it with typescript and then run webpack on the .js files. I've done some more investigating and there seem to be two separate issues. I'm gonna close this issue now and will create new issues tomorrow that are better explained.

**Comment by SonofNun15** [comment]
I'm running into this same issue and can't get past it at the moment... :disappointed:

**Comment by jbrantly** [comment]
@SonofNun15 Could you be more specific? Are you literally getting `Module build failed: Error: Cannot resolve module 'stream'`? It may make sense to open a new issue with a simple example.

**Comment by SonofNun15** [comment]
@jbrantly: Currently putting together a very simple public repo to demonstrate the issue. I will post once I am finished.

**Comment by SonofNun15** [comment]
@jbrantly: Check out this repository. Very simple, very clean. Demonstrates the issue. Let me know if I'm missing something important here or if this is a legitimate issue...
https://github.com/SonofNun15/typescript-library-test

**Comment by SonofNun15** [comment]
I created a proper issue to track this. https://github.com/jbrantly/ts-loader/issues/46 
Thanks!

**Comment by idododu** [comment]
try `externals` config.

I got `Module not found: Error: Can't resolve 'angular'` error when run `webpack` in command line.
my source code is:
```
import * as angular from 'angular'
// blablabla
```
after put below config in `webpack.config.js`, it works great now
```
externals: {
        angular: 'angular'
 },
```
