### ISSUE TITLE
Conditional Imports

### ISSUE THREAD

**Issue by deryl27** [jbrantly/ts-loader#31]
@jbrantly  
I was wondering if we can have a conditional imports  

if(isDebugMode)
{
   import('./a');
}

**Comment by jbrantly** [comment]
I created an example for how to do this: https://github.com/jbrantly/ts-loader/tree/master/test/conditionalRequire

**Comment by deryl27** [comment]
@jbrantly  the Example is using the "require" 

I was wondering if it is possible to import a module inside the 'if condition'

**Comment by jbrantly** [comment]
`require` is how you import a module. That example does import a module.
