### ISSUE TITLE
ES6 export default doesn't work with require.ensure

### ISSUE THREAD

**Issue by popealex** [jbrantly/ts-loader#33]
Howdy,

It looks like require.ensure doesn't work with export default.  If you were to take the [example] (https://github.com/jbrantly/ts-loader/tree/master/test/codeSplitting) and change c.ts and/or d.ts to use export default you should be able to repro the issue.  Example:

```javascript
a.ts:
export default 'a';

c.ts:
export default 'c';

app.ts:
import a from './a';
import b = require('./b');
// modules c and d won't actually be emitted as "require" calls here
// since they are not used directly. Instead, they are only referenced
// with "typeof". At this point, these statements are only for the
// benefit of the TypeScript type system.
import c from './c';
import d = require('./d');

console.log(a);
console.log(b);
require.ensure(['./c', './d'], function(require) {
	// These require calls are emitted (note these are NOT TypeScript
	// `import ... require` statements). `require.ensure` is defined in
	// require.d.ts. Webpack sees this and automatically puts c and d
	// into a separate chunk. 
	var c:string = <typeof c>require('./c');
	var d:string = <typeof d>require('./d');
	console.log(c);
	console.log(d);
});
```

Output: 
```javascript
bundle1.js:
	var a_1 = __webpack_require__(1);
	var b = __webpack_require__(2);
	console.log(a_1["default"]);
	console.log(b);
	__webpack_require__.e/* nsure */(1, function (require) {
	    // These require calls are emitted (note these are NOT TypeScript
	    // `import ... require` statements). `require.ensure` is defined in
	    // require.d.ts. Webpack sees this and automatically puts c and d
	    // into a separate chunk. 
	    var c = __webpack_require__(3);
	    var d = __webpack_require__(4);
	    console.log(c);
	    console.log(d);
	});

/***/ },
/* 1 */
/***/ function(module, exports) {

	exports["default"] = 'a';


/***/ },
/* 2 */
/***/ function(module, exports) {

	module.exports = 'b';


/***/ }

1.bundle.js:
webpackJsonp([1],[
/* 0 */,
/* 1 */,
/* 2 */,
/* 3 */
/***/ function(module, exports) {

	exports["default"] = 'c';


/***/ },
/* 4 */
/***/ function(module, exports) {

	module.exports = 'd';


/***/ }
]);

output:
a
b
Object {default: "c"}
d
```

The normal import works fine.  I've been unable to get anything working inside require.ensure.  Is this not yet supported?

**Comment by jbrantly** [comment]
Hmm, this is an interesting problem. Technically, to do dynamic loading in ES6 (code splitting) you would use `System.import`, but neither TypeScript nor webpack know about that. When you do `var c:string = <typeof c>require('./c');` TypeScript doesn't actually see that as a module require and therefore doesn't do the `c["default"]` conversion like it does for `a`. It's possible Babel could help here but I'd have to play around with it. I'll see if I can get something working.

In any case there's nothing the loader can do.

**Comment by jbrantly** [comment]
Actually, after thinking about this a minute longer, somehow supporting `System.import` won't really fix anything here. `System.import` doesn't support the syntax sugar over the default export anyways, so you wouldn't really be gaining anything by it. You need to grab the default export yourself either way.

```javascript
    console.log(c["default"]);
```

**Comment by popealex** [comment]
Grabbing the default export is definitely doable, but is quite a bit of a hack that needs to be repeated throughout the codebase wherever a split happens.  It's also a bit fragile, e.g. if the default export were to change you wouldn't see that at compile time.

I suppose the issue needs to be raised against typescript?

**Comment by jbrantly** [comment]
> It's also a bit fragile, e.g. if the default export were to change you wouldn't see that at compile time.

I think you would due to the `<typeof c>` part.

> I suppose the issue needs to be raised against typescript?

It's not a TypeScript issue, it's an ES6 issue. ES6 lacks syntactic sugar for the `default` export when using `System.import`. For example "code splitting" in idiomatic ES6 would look like this:

```javascript
// a.js
export default 'a';

// b.js
export default 'b';

// app.js
import a from './a';

console.log(a);

System.import('./b').then(b => console.log(b["default"]))
```

Note that you still need to access the `default` property explicitly. In other words it's similar to doing this:

```javascript
import * as b from './b';
```

Note here that I'm using `require.ensure` and `System.import` interchangeably.

**Comment by popealex** [comment]
>>It's also a bit fragile, e.g. if the default export were to change you wouldn't see that at compile time.

>I think you would due to the `<typeof c>` part.

I'm not sure that's true because that's an explicit cast without any safety. Try changing our example to:

```javascript
c.ts
//export default 'c';
export default function() {return 'c';};

app.ts:
var c:string = <typeof c>((<any>require('./c')).default);
```

Switching the comment in c.ts doesn't cause a compile time break.  Even explicitly checking for type doesn't seem to work:

```javascript
function doStuff(s: string) {
  return s + '_' + s;
}

// Prove the typechecker is working:
//doStuff(5);

...

// With or without explicit typing on 'c':
var c:string = <typeof c>((<any>require('./c')).default);
//var c = <typeof c>((<any>require('./c')).default);
doStuff(c);
```

I can't get typescript to complain when I change the export type in c.ts. If you're able to I would love to learn the trick! :)

**Comment by jbrantly** [comment]
This works correctly:

```typescript
import * as a from './a';
import * as b from './b';

require.ensure(['./a', './b'], function(require) {
    var aModule = <typeof a>require('./a');
    var bModule = <typeof b>require('./b');
    
    aModule["default"](); // error TS2349: Cannot invoke an expression whose type lacks a call signature.
    bModule["default"]();
});
```

**Comment by jbrantly** [comment]
The reason `var c:string = <typeof c>((<any>require('./c')).default);` wasn't quite working was because `typeof c` there actually refers to the variable `c` that you just created and not the module `c`. They need to have different names like in the example above.

**Comment by jbrantly** [comment]
As an alternative to the above syntax, you could also do this. Just depends on what style you want (and you can mix-and-match)

```typescript
import a from './a';
import b from './b';

require.ensure(['./a', './b'], function(require) {
    var aDefault = <typeof a>require('./a')["default"];
    var bDefault = <typeof b>require('./b')["default"];
    
    aDefault();
    bDefault();
});
```

**Comment by popealex** [comment]
Nice! You might want to clean up the example since I think it has the same bug?  You might also considering throwing 'export default' and one or both of these styles in there as well for future readers.

**Comment by jbrantly** [comment]
Yup, gonna fix the current example and also add an ES6 version.

**Comment by jbrantly** [comment]
FWIW, I think you can close the issue you opened with TypeScript. There's really not much more they can do here IMO.
