### ISSUE TITLE
Support for TypeScript JSX files (.tsx)

### ISSUE THREAD

**Issue by bjfletcher** [jbrantly/ts-loader#41]
TypeScript 1.6 has a new feature: support for JSX syntax.

This is especially useful for those who want to use the ReactJS framework.

This `ts-loader` gives the following error when I attempt to get it to compile `.tsx` files:

> `TS17004: Cannot use JSX unless the '--jsx' flag is provided.`

Do you think we could get the loader to add the `--jsx` flag if the file ends with `.tsx`?

If you want to test for yourself, just change version of TypeScript in the dependency list in `package.json` to `1.6.0-beta` and have a basic `.tsx` file:

````
export class Hello {
  function greet(s:string):void {
    // do nothing
  }
}
```

**Comment by jbrantly** [comment]
You should set the `jsx` flag yourself using tsconfig.json.

See https://github.com/jbrantly/ts-loader/tree/master/test/jsx for an example.

**Comment by bjfletcher** [comment]
@jbrantly That's fair enough, by the way, very many thanks for the excellent work around this. :)

**Comment by jbrantly** [comment]
NP! :smile:
