### ISSUE TITLE
Support for 1.6

### ISSUE THREAD

**Issue by raybooysen** [jbrantly/ts-loader#43]
Is there anything that needs updating to support 1.6?

Thanks!

**Comment by jbrantly** [comment]
Shouldn't be, nope. Did you run into an issue?

**Comment by jbrantly** [comment]
The nightly test [ran without issue](https://travis-ci.org/jbrantly/ts-loader/jobs/80760739) against 1.6 stable, so no known problems. I'll update the README to be more clear that 1.6 is explicitly supported.

**Comment by raybooysen** [comment]
Great, I was having issues with the new tsx file extensions with React, will test more today
