### ISSUE TITLE
Move under TypeStrong

### ISSUE THREAD

**Issue by basarat** [jbrantly/ts-loader#47]
Would you be willing to move this under TypeStrong. That would: 

 a) help ensure continued support
 b.) make more *defacto* (not that it isn't the case right now). 

I'd be happy to add you as an owner under the org

**Comment by jbrantly** [comment]
Yea I'm open to this. I've sent you a twitter PM with my email to discuss.

**Comment by basarat** [comment]
Awesome. Thanks :rose:

**Comment by blakeembrey** [comment]
@basarat Haha, thanks for this :smile:

@jbrantly I want to deprecate my loader in favour of pushing for a common one, do you mind if we start doing some PRs and fix some of the issues (if there are any still) on this loader? For reference, my loader is https://github.com/blakeembrey/typescript-simple-loader and I'm curious on the different implementation decisions. 

Also related, but I'd love to bring all the different options in sync - should I create a `meta` repo for those discussions? Just things like `compiler`, `project`, etc.

**Comment by jbrantly** [comment]
> do you mind if we start doing some PRs and fix some of the issues (if there are any still) on this loader

Absolutely! I'd love collaboration. I've kept an on-going private list of bugs/features. I'm only aware of two bugs right at the moment: #45 and another regarding error reporting that I've created a test case for but haven't published/fixed yet. I'll see about surfacing those items via issues.

I'll also stop directly committing code and instead create PRs and ping you @blakeembrey for review.

Regarding other discussions, I'm good with a meta repo so we can get on the same page.

**Comment by johnnyreilly** [comment]
This is brilliant!

**Comment by jbrantly** [comment]
@blakeembrey FYI, I've transferred all of my outstanding work to PRs/issues

**Comment by blakeembrey** [comment]
@jbrantly Awesome, cheers! Did you want to chat some time about the different approaches we took on the loaders? I'm curious, actually, about how you ended up with the resolver stuff. I can't really comment on whether there's too many issues/differences between them without doing a bunch more testing, but if we can add the `ignoreWarnings` option I could finally deprecate mine for this :smile:

**Comment by jbrantly** [comment]
@blakeembrey Yea definitely let's chat. Perhaps in the gitter room? I've started idling there.

Re: `ignoreWarnings` I opened #60
