### ISSUE TITLE
Support passing in additional arbitrary files

### ISSUE THREAD

**Issue by jbrantly** [jbrantly/ts-loader#6]
Creating this issue on behalf of @fdecampredon

We should be able to manually add additional files to the TypeScript compiler. This is roughly equivalent to passing multiple files to the `tsc` command.

**Comment by jbrantly** [comment]
@fdecampredon Check out the `additionalFiles` test. Does this satisfy what you're looking for?

**Comment by fdecampredon** [comment]
Yup sure pretty cool thanks :)

**Comment by jbrantly** [comment]
Published in v0.3.2
